DROP TABLE IF EXISTS Storytelling;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Situation;
DROP TABLE IF EXISTS Option;
DROP TABLE IF EXISTS PlayerBackgroundOption;
DROP TABLE IF EXISTS PlayerClassOption;

CREATE TABLE IF NOT EXISTS PlayerClassOption(
    Id VARCHAR(36),
    Name VARCHAR(255),
    Description TEXT
);
